# Generated by Django 5.2 on 2025-04-12 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер машины')),
                ('car_model', models.CharField(max_length=100, verbose_name='Модель машины')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Parkings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_place', models.PositiveIntegerField(unique=True, verbose_name='Парковочное место')),
                ('status', models.BooleanField(default=True, verbose_name='Статус места: занято')),
                ('time_in', models.DateTimeField(auto_now_add=True, verbose_name='Время въезда')),
                ('time_out', models.DateTimeField(auto_now=True, verbose_name='Время выезда')),
                ('pay', models.BooleanField(default=False, verbose_name='Статус оплаты')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Стоимость оплаты')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.cars', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Парковочное место',
                'verbose_name_plural': 'Парковочное место',
            },
        ),
    ]
