# Generated by Django 5.2 on 2025-04-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='car_model',
        ),
        migrations.AlterField(
            model_name='cars',
            name='number',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Номер машины'),
        ),
    ]
