# Generated by Django 5.2 on 2025-04-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_remove_cars_car_model_alter_cars_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkings',
            name='parking_place',
        ),
        migrations.RemoveField(
            model_name='parkings',
            name='status',
        ),
        migrations.AlterField(
            model_name='parkings',
            name='pay',
            field=models.BooleanField(blank=True, default=False, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='parkings',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Стоимость оплаты'),
        ),
    ]
