# Generated by Django 5.2 on 2025-04-13 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_remove_parkings_parking_place_remove_parkings_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkings',
            name='time_out',
        ),
    ]
